# Fly configuration for the front-end static site
# If you already have this app on Fly, keep the existing app value.
app = "linkdms-frontend"
primary_region = "ord"

[build]

[env]
# Nginx listens on port 80 inside the container; expose the same.
PORT = "80"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0