# fly.toml app configuration file for linkdms-worker
# INTERNAL-ONLY SERVICE - Not accessible from public internet

app = 'linkdms-worker'
primary_region = 'ord'

[build]
  dockerfile = "Dockerfile"

# Internal-only service (no public HTTP access)
[[services]]
  internal_port = 3000
  protocol = "tcp"
  
  [[services.ports]]
    port = 3000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
