# fly.toml app configuration file for linkdms-worker
# INTERNAL-ONLY SERVICE - Not accessible from public internet

app = 'linkdms-worker'
primary_region = 'ord'

[build]
  dockerfile = "Dockerfile"

[env]
  LOG_LEVEL = "debug"

# Service definition
[[services]]
  internal_port = 3000
  protocol = "tcp"
  # Let Fly auto-start the machine on first request and auto-stop on idle
  auto_start = true
  auto_stop = true

  # --- Public exposure (added for Edge Function access) ---
  # HTTP (port 80) will redirect to HTTPS automatically
  [[services.ports]]
    port = 80
    handlers = ["http"]

  # HTTPS endpoint
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
