// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use Vite's special env variables. These come from your .env.local file.
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://ebgezhrvlqvornidwfqv.supabase.co";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZ2V6aHJ2bHF2b3JuaWR3ZnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjgyOTQsImV4cCI6MjA2NDE0NDI5NH0.ZW6H2OyQXsxajQpafI8Rnrc-br3-KPnuWmLIxLn1OFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(supabaseUrl, supabaseAnonKey);